variable project-name {}
variable region {}
variable cidr-block-vpc {}
variable cidr-block-subnet {}               
variable availability-zone {}             
variable azure-cidr-block {}
variable instance-type {}
variable image-name-linux {}
variable image-name-windows {}