appName: checkoutservice
appImage: <your_app_image_link>/checkoutservice
appVersion: "1.1"
appReplicas: 2
containerPort: 5050
containerEnvVars:
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
secretName: ecrcred
livenessPeriodSeconds: 5
readinessPeriodSeconds: 5
cpuRequests: 100m
memRequests: 64Mi
cpuLimits: 200m
memLimits: 128Mi

portsName: grpc
servicePort: 5050