appName: paymentservice
appImage: <your_app_image_link>/paymentservice
appVersion: "1.1"
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
secretName: ecrcred
livenessPeriodSeconds: 5
readinessPeriodSeconds: 5
cpuRequests: 75m
memRequests: 64Mi
cpuLimits: 150m
memLimits: 128Mi

portsName: grpc
servicePort: 50051