appName: recommendationservice
appImage: <your_app_image_link>/recommendationservice
appVersion: "1.1"
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
secretName: ecrcred
livenessPeriodSeconds: 5
readinessPeriodSeconds: 5
cpuRequests: 100m
memRequests: 64Mi
cpuLimits: 200m
memLimits: 128Mi

portsName: grpc
servicePort: 8080